### ISSUE TITLE
use videojs for video tweets

### ISSUE THREAD

**Issue by mcorb** [mannynotfound/react-tweet#1]
Twitter.com uses the VideoJS project to handle video. The current <video> tag can be replaced with this React component for feature parity:

  https://github.com/esportsguy/react-videojs

**Comment by mannynotfound** [comment]
Bless you for this. :pray:

**Comment by mannynotfound** [comment]
@mcorb Added [here](https://github.com/artnotfound/react-tweet/commit/4d49a852c8fcd2909b5934de3f34c03be4fcb878) and updated the [demo page](https://react-tweet.herokuapp.com/). looks hot. thanks.
