### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by Torone** [mannynotfound/react-tweet#11]
Hi,

Once running `npm install` to install dependencies from `package.json` I see the following error:

```
$ npm install
npm WARN react-tweet@1.1.1 requires a peer of react-dom@15.5.4 but none was installed.
npm WARN react-videojs@0.0.2 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-videojs@0.0.2 requires a peer of react-dom@^0.14.0 but none was installed.
```

Cheers

**Comment by mannynotfound** [comment]
seems like your version of react may not be high enough? what version of react are you using in your `package.json`?

**Comment by Torone** [comment]
latest, thanks!

**Comment by pan100** [comment]
This is still a problem. Dependencies are falling behind latest versions.

**Comment by pan100** [comment]
My commit removes the first but the 2nd is in a different project.

**Comment by mannynotfound** [comment]
@Torone @pan100 can yall try version `1.2.1` and see if it resolved issues? Merged https://github.com/mannynotfound/react-tweet/pull/15
