### ISSUE TITLE
VideoJS is creating error 

### ISSUE THREAD

**Issue by murillio4** [mannynotfound/react-tweet#17]
`React.createClass` in VideoJS is creating compiling errors as it is deprecated

**Comment by pkpp1233** [comment]
The specific error I'm getting is 

```
index.js:8 Uncaught TypeError: React.createClass is not a function
    at Object.hasOwn (index.js:8)
    at __webpack_require__ (bootstrap 315b4bbde22bb0f8ad36:19)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap 315b4bbde22bb0f8ad36:19)
    at Object.<anonymous> (Video.js:23)
    at __webpack_require__ (bootstrap 315b4bbde22bb0f8ad36:19)
    at Object.exports.__esModule (Media.js:25)
    at __webpack_require__ (bootstrap 315b4bbde22bb0f8ad36:19)
    at Object.exports.__esModule (Tweet.js:31)
    at __webpack_require__ (bootstrap 315b4bbde22bb0f8ad36:19)
```

**Comment by mcshiz** [comment]
Its because with react 16 createClass is deprecated.
I just submitted a pull request with a fix here https://github.com/mannynotfound/react-tweet/pull/18

**Comment by FloatingGhost** [comment]
This is active again as of 1.5.0, again caused by VideoJS

**Comment by mannynotfound** [comment]
@FloatingGhost seems to be working for me locally. can you include steps to reproduce error youre encountering?

**Comment by FloatingGhost** [comment]
Quickest and easiest way from scratch

```
mkdir reproduce
cd reproduce
create-react-app . 
yarn add react-tweet
vi src/App.js
```
In App.js
```js
import Tweet from "react-tweet";

render() {
  ...
  <Tweet />
  ...
}
```

start (`yarn start`) and navigate to dev server

Screenshot attached

![2018-03-22-165829](https://user-images.githubusercontent.com/4086403/37785598-7d43f85a-2df2-11e8-8ccf-957549d96ef3.png)

**Comment by mannynotfound** [comment]
@FloatingGhost just tried a fix. can you use the beta version and let me know if problem persists?

`npm install react-tweet@beta`

**Comment by FloatingGhost** [comment]
nice! That resolved it. Thanks~

**Comment by mannynotfound** [comment]
@FloatingGhost cool. should be live now on master and npm version `1.7.0`
