### ISSUE TITLE
Can't resolve './lib/Tweet/Tweet'

### ISSUE THREAD

**Issue by KevinFarmer** [mannynotfound/react-tweet#22]
During the fall I was using the react-tweet library for a project with no problems. After coming back to it, I am now getting this error when trying to compile my React webpage:

ERROR in ./~/react-tweet/index.js
Module not found: Error: Can't resolve './lib/Tweet/Tweet'

Something seems to have changed since November which broke this for me

**Comment by KevinFarmer** [comment]
I think that it is a dependency issue, see here: https://github.com/mannynotfound/react-tweet/pull/23

**Comment by KevinFarmer** [comment]
It doesn't seem to be the dependency issue. For some reason, the ./lib folder is not being created or populated under node_modules/react-tweet/

**Comment by KevinFarmer** [comment]
[2018-01-18T04_09_05_936Z-debug.log](https://github.com/mannynotfound/react-tweet/files/1641614/2018-01-18T04_09_05_936Z-debug.log)

The build:js script seems to be failing on my system

**Comment by mannynotfound** [comment]
@KevinFarmer hey Kevin this is probably a npm version issue. I too am seeing the build error on npm `5.5.1`. Taking a look, what version of npm are you running?

**Comment by KevinFarmer** [comment]
I am on version 4.2.0

**Comment by mannynotfound** [comment]
@KevinFarmer Hey Kevin, ive re-configured the build setup to try to fix this. Can you try doing `npm install react-tweet@beta` and let me know if that works out for you? If it looks good ill update the latest tag to this version

**Comment by KevinFarmer** [comment]
@mannynotfound I'm getting a different build error now, seems like a dependency issue:

ERROR in ./~/react-tweet/lib/Tweet/Context.js
Module not found: Error: Can't resolve 'babel-runtime/helpers/extends' in '/home/kfarmer/cs98/17f-smr/node_modules/react-tweet/lib/Tweet'
 @ ./~/react-tweet/lib/Tweet/Context.js 1:0-53
 @ ./~/react-tweet/lib/Tweet/Tweet.js
 @ ./~/react-tweet/index.js
 @ ./src/containers/cleanup-search.js
 @ ./src/containers/app-cont.js
 @ ./src/components/app.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src

The same error is repeated for Header.js, Media.js, Quote.js and Footer.js

**Comment by mannynotfound** [comment]
@KevinFarmer is that when running npm install or when trying to run the local webpack server?

**Comment by mannynotfound** [comment]
@KevinFarmer that error must be from running your project with react-tweet then, but the install works?

**Comment by KevinFarmer** [comment]
Yes the install works, the error is from running it

**Comment by mannynotfound** [comment]
@KevinFarmer Gotcha, I think i got it working. can you try `npm install react-tweet@beta` (version `1.3.6`) again

**Comment by KevinFarmer** [comment]
It works!

**Comment by mannynotfound** [comment]
@KevinFarmer sweet. will update main `latest` version soon
