### ISSUE TITLE
Could react be a peerDependency?

### ISSUE THREAD

**Issue by chmac** [mannynotfound/react-tweet#4]
I was checking out `package.json` and noticed that react is a dependency, so now my `node_modules` folder has 2 copies of react, your `0.14` version and my main `0.15` version.

Would it be possible to switch `react` to being a `peerDependency` instead? My npm packaging fu is not strong enough to say outright that it **is** possible, maybe it has other implications. I've seen quite a few packages using this approach with react, so I guess it is possible somehow, just not sure how much work is involved in getting there...

**Comment by mannynotfound** [comment]
@chmac Hey there. Are you using webpack? If so you can use `resolve` in your config to only load 1 copy of React ever. You can see this in action here https://github.com/mannynotfound/react-tweet/blob/master/webpack.config.js#L33-L37. If that doesnt work I wouldnt mind a pull request to either make React a peer dependency or just upgrade to React 15 :). Let me know

**Comment by chmac** [comment]
Interesting, didn't know webpack cpuld do that. Smart!

We're using meteor, so don't have access to so many options in the build system. Will explore the PR route...
